/**
 * Firestore Seed Script — Populates 'services' collection with realistic salon data
 * Run with: node seed.js
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, doc, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDdgn9XnjtJp9i7GlWmCUmuze8vHXATb2k",
  authDomain: "maison-salon-at-home.firebaseapp.com",
  projectId: "maison-salon-at-home",
  storageBucket: "maison-salon-at-home.firebasestorage.app",
  messagingSenderId: "18321783031",
  appId: "1:18321783031:web:498e0265f46e5ff1467bf2"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const services = [
  // ===================== WOMEN'S SERVICES =====================
  {
    serviceId: 'w-rica-wax-combo',
    title: 'Rica Waxing - Full Arms + Full Legs + Underarms',
    gender: 'women',
    category: 'Waxing',
    price: 1299,
    originalPrice: 1599,
    durationMinutes: 70,
    rating: 4.8,
    reviewCount: 4234,
    imageUrl: 'https://images.pexels.com/photos/6763618/pexels-photo-6763618.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Pre-Wax Prep', desc: 'Skin cleansed with antiseptic pre-wax powder to ensure a clean, dry surface for best wax adhesion' },
      { step: 2, title: 'Rica Wax Application', desc: 'Italian-formula Rica wax with olive oil & almond extract applied at body temperature—no burning' },
      { step: 3, title: 'Strip Removal', desc: 'Muslin strips pulled swiftly against hair growth direction for clean root-level removal' },
      { step: 4, title: 'Post-Wax Soothing', desc: 'Cooling post-wax lotion applied to calm redness and close pores instantly' },
    ],
    procedureSteps: [
      { step: 1, title: 'Cleanse & Prep', image: '' },
      { step: 2, title: 'Wax Application', image: '' },
      { step: 3, title: 'Strip Removal', image: '' },
      { step: 4, title: 'Post Care', image: '' },
    ],
  },
  {
    serviceId: 'w-rica-full-body-wax',
    title: 'Full Body Rica Waxing (Arms + Legs + Underarms + Bikini Line)',
    gender: 'women',
    category: 'Waxing',
    price: 1999,
    originalPrice: 2499,
    durationMinutes: 90,
    rating: 4.9,
    reviewCount: 2876,
    imageUrl: 'https://images.pexels.com/photos/6763120/pexels-photo-6763120.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Full Body Consultation', desc: 'Technician assesses skin sensitivity and selects the appropriate wax grade for each zone' },
      { step: 2, title: 'Zone-Wise Rica Application', desc: 'Rica wax applied zone by zone from arms to legs, ensuring even coverage and minimal discomfort' },
      { step: 3, title: 'Bikini Line Care', desc: 'Extra gentle technique using hypoallergenic Rica formula for the sensitive bikini area' },
      { step: 4, title: 'Soothe & Hydrate', desc: 'Aloe vera and vitamin E post-wax lotion applied on all treated areas to reduce inflammation' },
    ],
    procedureSteps: [
      { step: 1, title: 'Skin Assessment', image: '' },
      { step: 2, title: 'Arms & Underarms', image: '' },
      { step: 3, title: 'Legs', image: '' },
      { step: 4, title: 'Bikini Line', image: '' },
      { step: 5, title: 'Post-Care', image: '' },
    ],
  },
  {
    serviceId: 'w-rica-half-legs',
    title: 'Rica Waxing - Half Legs + Underarms + Upper Lips',
    gender: 'women',
    category: 'Waxing',
    price: 699,
    originalPrice: 899,
    durationMinutes: 40,
    rating: 4.7,
    reviewCount: 6102,
    imageUrl: 'https://images.pexels.com/photos/5240782/pexels-photo-5240782.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Skin Prep', desc: 'Pre-wax powder applied on half legs and underarms to absorb moisture' },
      { step: 2, title: 'Rica Application', desc: 'Rica wax spread evenly on half legs, underarms, and upper lip area' },
      { step: 3, title: 'Strip Pull', desc: 'Precise strip removal ensures clean finish with minimal skin irritation' },
      { step: 4, title: 'Cool Down', desc: 'Cooling gel applied to soothe post-wax skin and prevent bumps' },
    ],
    procedureSteps: [
      { step: 1, title: 'Prep Skin', image: '' },
      { step: 2, title: 'Apply Wax', image: '' },
      { step: 3, title: 'Remove Strips', image: '' },
      { step: 4, title: 'Soothe', image: '' },
    ],
  },
  {
    serviceId: 'w-o3-pearl-facial',
    title: 'O3+ Pearl Facial',
    gender: 'women',
    category: 'Facial',
    price: 1649,
    originalPrice: 1999,
    durationMinutes: 60,
    rating: 4.8,
    reviewCount: 3512,
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Double Cleanse', desc: 'O3+ milk cleanser followed by foaming face wash to remove oil, dirt, and makeup residue' },
      { step: 2, title: 'D-Tan Scrub', desc: 'O3+ oat and walnut scrub exfoliates dead cells, visibly brightening the complexion' },
      { step: 3, title: 'Pearl Massage Cream', desc: '10-minute pearl-infused massage cream application boosts circulation and restores natural radiance' },
      { step: 4, title: 'Vitamin C Pack', desc: 'O3+ vitamin C gel mask applied for 15 minutes for deep brightening and antioxidant boost' },
      { step: 5, title: 'Toner + Moisturizer', desc: 'pH-balancing toner followed by day cream for long-lasting hydration and sun protection' },
    ],
    procedureSteps: [
      { step: 1, title: 'Cleanse', image: '' },
      { step: 2, title: 'Exfoliate', image: '' },
      { step: 3, title: 'Pearl Massage', image: '' },
      { step: 4, title: 'Vitamin C Mask', image: '' },
      { step: 5, title: 'Tone & Moisturize', image: '' },
    ],
  },
  {
    serviceId: 'w-hydrafacial',
    title: 'HydraFacial - HydraClean + Glow Peel',
    gender: 'women',
    category: 'Facial',
    price: 2149,
    originalPrice: 2699,
    durationMinutes: 75,
    rating: 4.9,
    reviewCount: 2184,
    imageUrl: 'https://images.pexels.com/photos/29189893/pexels-photo-29189893.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'HydraClean', desc: 'Patented vortex-cleansing tip removes dead skin cells and opens pores while infusing hydrating serums simultaneously' },
      { step: 2, title: 'Glow Peel', desc: 'Glycolic and salicylic acid blend loosens debris from pores without any irritation or downtime' },
      { step: 3, title: 'Extraction', desc: 'Painless automated extraction removes blackheads and whiteheads in seconds using vacuum suction' },
      { step: 4, title: 'Serum Infusion', desc: 'Hyaluronic acid, peptides, and antioxidants infused deep into the skin for lasting hydration' },
      { step: 5, title: 'LED Light Therapy', desc: 'Red LED stimulates collagen; blue LED targets acne-causing bacteria—10 minutes of targeted healing' },
    ],
    procedureSteps: [
      { step: 1, title: 'HydraClean', image: '' },
      { step: 2, title: 'Glow Peel', image: '' },
      { step: 3, title: 'Extraction', image: '' },
      { step: 4, title: 'Serum Infuse', image: '' },
      { step: 5, title: 'LED Therapy', image: '' },
    ],
  },
  {
    serviceId: 'w-fruit-cleanup',
    title: 'Fruit Cleanup - Brightening & Tan Removal',
    gender: 'women',
    category: 'Cleanup',
    price: 1299,
    originalPrice: 1599,
    durationMinutes: 30,
    rating: 4.6,
    reviewCount: 7820,
    imageUrl: 'https://images.pexels.com/photos/11179579/pexels-photo-11179579.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Milk Cleanse', desc: 'Vitamin-enriched milk cleanser removes sunscreen, oil, and environmental pollutants' },
      { step: 2, title: 'Fruit Enzyme Scrub', desc: 'Papaya and pineapple enzyme scrub dissolves dead skin cells and reduces tan in 5 minutes' },
      { step: 3, title: 'Brightening Pack', desc: 'Kojic acid and saffron face pack applied for 15 minutes for instant glow and de-tanning' },
      { step: 4, title: 'Moisturize & SPF', desc: 'Lightweight SPF 30 moisturizer sealed in all the goodness for an all-day glow' },
    ],
    procedureSteps: [
      { step: 1, title: 'Cleanse', image: '' },
      { step: 2, title: 'Enzyme Scrub', image: '' },
      { step: 3, title: 'Brightening Pack', image: '' },
      { step: 4, title: 'Moisturize', image: '' },
    ],
  },
  {
    serviceId: 'w-o3-cleanup',
    title: "O3+ Anti-Tan Cleanup",
    gender: 'women',
    category: 'Cleanup',
    price: 1499,
    originalPrice: 1899,
    durationMinutes: 45,
    rating: 4.7,
    reviewCount: 5340,
    imageUrl: 'https://images.pexels.com/photos/29189920/pexels-photo-29189920.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Deep Cleanse', desc: 'O3+ charcoal cleanser draws out toxins and clears blackheads from the first wash' },
      { step: 2, title: 'AHA Scrub', desc: 'Alpha hydroxy acid scrub removes tanned, dull skin for immediate brightness' },
      { step: 3, title: 'Steam + Extraction', desc: 'Herbal steam opens pores followed by professional blackhead and whitehead extraction' },
      { step: 4, title: 'Anti-Tan Pack', desc: 'Licorice and mulberry anti-tan mask sits for 15 minutes reducing pigmentation visibly' },
      { step: 5, title: 'Sunscreen Finish', desc: 'O3+ SPF 50 PA+++ sunscreen applied to protect freshly treated skin' },
    ],
    procedureSteps: [
      { step: 1, title: 'Cleanse', image: '' },
      { step: 2, title: 'AHA Scrub', image: '' },
      { step: 3, title: 'Steam', image: '' },
      { step: 4, title: 'Anti-Tan Mask', image: '' },
      { step: 5, title: 'SPF Finish', image: '' },
    ],
  },
  {
    serviceId: 'w-classic-mani-pedi',
    title: 'Classic Manicure + Pedicure',
    gender: 'women',
    category: 'Manicure & Pedicure',
    price: 1849,
    originalPrice: 2299,
    durationMinutes: 80,
    rating: 4.7,
    reviewCount: 3890,
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=400&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Soak & Soften', desc: 'Warm rose milk soak for hands and feet softens cuticles and hydrates cracked heels' },
      { step: 2, title: 'Nail Shaping', desc: 'Cuticles trimmed and pushed back; nails filed and buffed to your preferred shape' },
      { step: 3, title: 'Sea Salt Scrub', desc: 'Dead sea salt scrub exfoliates hands and feet, removing dead skin and improving texture' },
      { step: 4, title: 'Paraffin Massage', desc: 'Warm paraffin wax seals in moisture while a relaxing hand and foot massage follows' },
      { step: 5, title: 'Nail Paint Finish', desc: 'Base coat + 2 coats of regular nail paint + top coat; choice of 50+ shades' },
    ],
    procedureSteps: [
      { step: 1, title: 'Soak', image: '' },
      { step: 2, title: 'Shape Nails', image: '' },
      { step: 3, title: 'Scrub', image: '' },
      { step: 4, title: 'Massage', image: '' },
      { step: 5, title: 'Nail Paint', image: '' },
    ],
  },
  {
    serviceId: 'w-spa-mani-pedi',
    title: 'Spa Manicure + Pedicure with Gel Polish',
    gender: 'women',
    category: 'Manicure & Pedicure',
    price: 2289,
    originalPrice: 2799,
    durationMinutes: 100,
    rating: 4.8,
    reviewCount: 2140,
    imageUrl: 'https://images.pexels.com/photos/4155019/pexels-photo-4155019.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Detox Soak', desc: 'Fizzing detox bath with essential oils removes built-up grime and relaxes tired muscles' },
      { step: 2, title: 'Callus Removal', desc: 'Professional callus remover and file used on heels and pressure points for salon-smooth feet' },
      { step: 3, title: 'Vitamin C Scrub', desc: 'Citrus-enzyme scrub brightens hands and feet, reducing pigmentation and tan lines' },
      { step: 4, title: 'Mask + Hot Towel Wrap', desc: '15-minute nourishing mask with hot towel wrap for deep hydration and pore cleansing' },
      { step: 5, title: 'Gel Polish Application', desc: 'Long-lasting LED-cured gel polish applied for chip-free nails up to 14 days' },
    ],
    procedureSteps: [
      { step: 1, title: 'Detox Soak', image: '' },
      { step: 2, title: 'Callus Remove', image: '' },
      { step: 3, title: 'Scrub', image: '' },
      { step: 4, title: 'Mask Wrap', image: '' },
      { step: 5, title: 'Gel Polish', image: '' },
    ],
  },
  {
    serviceId: 'w-eyebrow-threading',
    title: 'Eyebrows + Upper Lip Threading',
    gender: 'women',
    category: 'Threading',
    price: 149,
    originalPrice: 199,
    durationMinutes: 15,
    rating: 4.5,
    reviewCount: 12450,
    imageUrl: 'https://images.pexels.com/photos/6135615/pexels-photo-6135615.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Brow Mapping', desc: 'Face shape assessed to determine ideal brow arch, thickness, and tail length' },
      { step: 2, title: 'Precision Threading', desc: 'Twisted thread technique removes hair at the follicle level for sharp, clean lines' },
      { step: 3, title: 'Upper Lip Clear', desc: 'Upper lip fine hair removed with threading for a smooth, hair-free finish' },
      { step: 4, title: 'Soothe with Rose Water', desc: 'Chilled rose water applied to calm redness and close pores immediately after threading' },
    ],
    procedureSteps: [
      { step: 1, title: 'Brow Mapping', image: '' },
      { step: 2, title: 'Eyebrow Thread', image: '' },
      { step: 3, title: 'Upper Lip Thread', image: '' },
      { step: 4, title: 'Soothe', image: '' },
    ],
  },
  {
    serviceId: 'w-full-face-threading',
    title: 'Full Face Threading (Eyebrows + Upperlip + Chin + Forehead)',
    gender: 'women',
    category: 'Threading',
    price: 249,
    originalPrice: 349,
    durationMinutes: 25,
    rating: 4.6,
    reviewCount: 8920,
    imageUrl: 'https://images.pexels.com/photos/8558244/pexels-photo-8558244.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Consultation', desc: 'Discuss desired brow shape and facial hair concerns before beginning' },
      { step: 2, title: 'Brow Threading', desc: 'Precise brow arch created through expert thread technique tailored to face shape' },
      { step: 3, title: 'Face Threading', desc: 'Upper lip, chin, and forehead fine hair removed with swift threading strokes' },
      { step: 4, title: 'Cooling Finish', desc: 'Ice cube or rose water applied to instantly reduce redness and sensitivity' },
    ],
    procedureSteps: [
      { step: 1, title: 'Consult', image: '' },
      { step: 2, title: 'Brows', image: '' },
      { step: 3, title: 'Face Thread', image: '' },
      { step: 4, title: 'Cool Down', image: '' },
    ],
  },
  {
    serviceId: 'w-hair-spa',
    title: 'Hair Spa + Blow Dry (Shoulder Length)',
    gender: 'women',
    category: 'Hair',
    price: 1099,
    originalPrice: 1399,
    durationMinutes: 60,
    rating: 4.7,
    reviewCount: 4120,
    imageUrl: 'https://images.pexels.com/photos/10028673/pexels-photo-10028673.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Scalp Assessment', desc: 'Hair type and scalp condition evaluated to select the correct spa treatment variant' },
      { step: 2, title: 'Clarifying Shampoo', desc: 'Sulfate-free shampoo used to remove product buildup and prep hair for treatment absorption' },
      { step: 3, title: 'Hair Mask Application', desc: 'Deep conditioning protein/keratin mask applied strand by strand, combed through with wide-tooth comb' },
      { step: 4, title: 'Scalp Massage', desc: '15-minute warm oil scalp massage improves blood circulation and stimulates hair growth' },
      { step: 5, title: 'Blow Dry & Style', desc: 'Professional blow dry with heat protectant spray and round brush for smooth, frizz-free finish' },
    ],
    procedureSteps: [
      { step: 1, title: 'Assessment', image: '' },
      { step: 2, title: 'Shampoo', image: '' },
      { step: 3, title: 'Mask', image: '' },
      { step: 4, title: 'Scalp Massage', image: '' },
      { step: 5, title: 'Blow Dry', image: '' },
    ],
  },
  {
    serviceId: 'w-keratin-smoothening',
    title: 'Keratin Smoothening Treatment (Shoulder Length)',
    gender: 'women',
    category: 'Hair',
    price: 4999,
    originalPrice: 5999,
    durationMinutes: 120,
    rating: 4.8,
    reviewCount: 1870,
    imageUrl: 'https://images.pexels.com/photos/23349909/pexels-photo-23349909.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Clarifying Wash', desc: 'Deep-cleansing shampoo opens the hair cuticle for maximum keratin penetration' },
      { step: 2, title: 'Keratin Application', desc: 'Brazilian keratin formula applied section by section from root to tip with a fine-tooth comb' },
      { step: 3, title: 'Processing Time', desc: 'Keratin left to absorb into the cortex for 30 minutes under a shower cap' },
      { step: 4, title: 'Flat Iron Sealing', desc: 'High-heat flat iron at 230°C seals the keratin into each strand for lasting smoothness' },
      { step: 5, title: 'After-Care Advice', desc: 'Post-treatment care instructions given including 72-hour wash-free period for best results' },
    ],
    procedureSteps: [
      { step: 1, title: 'Clarify', image: '' },
      { step: 2, title: 'Apply Keratin', image: '' },
      { step: 3, title: 'Process', image: '' },
      { step: 4, title: 'Iron Seal', image: '' },
      { step: 5, title: 'After-Care', image: '' },
    ],
  },
  {
    serviceId: 'w-swedish-massage',
    title: 'Swedish Full Body Massage (60 min)',
    gender: 'women',
    category: 'Massage',
    price: 1799,
    originalPrice: 2199,
    durationMinutes: 60,
    rating: 4.8,
    reviewCount: 3220,
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Consultation & Oil Selection', desc: 'Therapist discusses target areas and selects from lavender, eucalyptus, or coconut carrier oil blend' },
      { step: 2, title: 'Effleurage Warm-Up', desc: 'Long, gliding strokes over the entire body warm up muscles and increase circulation' },
      { step: 3, title: 'Deep Tissue Work', desc: 'Petrissage kneading technique targets knots in shoulders, back, and glutes for deep tension release' },
      { step: 4, title: 'Tapotement', desc: 'Rhythmic percussion strokes energize muscles and stimulate lymphatic drainage' },
      { step: 5, title: 'Cooling Wind-Down', desc: 'Light feathering strokes bring the body to a relaxed state; peppermint cooling mist applied' },
    ],
    procedureSteps: [
      { step: 1, title: 'Oil Select', image: '' },
      { step: 2, title: 'Warm-Up Strokes', image: '' },
      { step: 3, title: 'Deep Tissue', image: '' },
      { step: 4, title: 'Tapotement', image: '' },
      { step: 5, title: 'Cool Down', image: '' },
    ],
  },

  // ===================== MEN'S SERVICES =====================
  {
    serviceId: 'm-classic-haircut',
    title: 'Classic Haircut (Regular / Fade)',
    gender: 'men',
    category: 'Haircut',
    price: 399,
    originalPrice: 499,
    durationMinutes: 30,
    rating: 4.6,
    reviewCount: 9840,
    imageUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=600&h=400&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Consultation', desc: 'Face shape analysis and discussion of preferred cut—regular, fade, undercut, or taper' },
      { step: 2, title: 'Shampoo & Condition', desc: 'Charcoal shampoo + conditioning mask applied to remove buildup and create clean, workable hair' },
      { step: 3, title: 'Precision Cut', desc: 'Scissors-over-comb and clipper technique delivers your chosen style with clean edges' },
      { step: 4, title: 'Finish & Style', desc: 'Matte clay, pomade, or wax applied per preference; final touch-up with razor for crisp lines' },
    ],
    procedureSteps: [
      { step: 1, title: 'Consult', image: '' },
      { step: 2, title: 'Wash', image: '' },
      { step: 3, title: 'Cut', image: '' },
      { step: 4, title: 'Style', image: '' },
    ],
  },
  {
    serviceId: 'm-haircut-beard-massage',
    title: 'Haircut + Beard Trim + Head Massage',
    gender: 'men',
    category: 'Haircut',
    price: 649,
    originalPrice: 799,
    durationMinutes: 50,
    rating: 4.8,
    reviewCount: 6720,
    imageUrl: 'https://images.pexels.com/photos/27497972/pexels-photo-27497972.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Scalp Wash', desc: 'Deep-cleansing shampoo followed by conditioner to prep hair for cutting and scalp massage' },
      { step: 2, title: 'Haircut', desc: 'Precision cut to desired style with taper, fade, or scissor finish based on consultation' },
      { step: 3, title: 'Beard Trim', desc: 'Clippers and scissors shape the beard to your preferred length with straight-razor edge cleanup' },
      { step: 4, title: 'Head Massage', desc: '10-minute warm coconut oil head massage focusing on scalp pressure points to reduce stress' },
      { step: 5, title: 'Blow Dry & Style', desc: 'Hair blow dried and styled to complete the look' },
    ],
    procedureSteps: [
      { step: 1, title: 'Wash', image: '' },
      { step: 2, title: 'Haircut', image: '' },
      { step: 3, title: 'Beard Trim', image: '' },
      { step: 4, title: 'Head Massage', image: '' },
      { step: 5, title: 'Style', image: '' },
    ],
  },
  {
    serviceId: 'm-beard-trim',
    title: 'Beard Trim + Shaping',
    gender: 'men',
    category: 'Beard & Grooming',
    price: 249,
    originalPrice: 349,
    durationMinutes: 20,
    rating: 4.5,
    reviewCount: 11230,
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&h=400&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Beard Wash', desc: 'Beard cleansed with beard-specific shampoo to remove food particles, dirt, and oil buildup' },
      { step: 2, title: 'Comb & Detangle', desc: 'Wide-tooth beard comb detangles and evens out beard for precise trimming' },
      { step: 3, title: 'Trim & Shape', desc: 'Clippers used to set desired length; scissors refine shape, taper cheeks, and define neckline' },
      { step: 4, title: 'Beard Oil Finish', desc: 'Argan and jojoba beard oil massaged in to soften, condition, and add healthy shine' },
    ],
    procedureSteps: [
      { step: 1, title: 'Wash', image: '' },
      { step: 2, title: 'Comb', image: '' },
      { step: 3, title: 'Trim & Shape', image: '' },
      { step: 4, title: 'Oil Finish', image: '' },
    ],
  },
  {
    serviceId: 'm-hot-towel-shave',
    title: 'Hot Towel Shave + Beard Contour',
    gender: 'men',
    category: 'Beard & Grooming',
    price: 449,
    originalPrice: 599,
    durationMinutes: 30,
    rating: 4.7,
    reviewCount: 5430,
    imageUrl: 'https://images.pexels.com/photos/16553361/pexels-photo-16553361.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Hot Towel Prep', desc: 'Steaming hot towel wrapped around face for 5 minutes to open pores and soften coarse stubble' },
      { step: 2, title: 'Pre-Shave Oil', desc: 'Pre-shave oil massaged into stubble to create a protective layer and allow razor to glide smoothly' },
      { step: 3, title: 'Shaving Cream Lather', desc: 'Rich shaving cream worked into thick lather with a badger brush for cushioned blade glide' },
      { step: 4, title: 'Straight Razor Shave', desc: 'Precise straight razor shave with multiple passes for baby-smooth skin with zero nicks' },
      { step: 5, title: 'Aftershave Balm', desc: 'Alcohol-free aftershave balm applied to close pores, prevent razor bumps, and soothe skin' },
    ],
    procedureSteps: [
      { step: 1, title: 'Hot Towel', image: '' },
      { step: 2, title: 'Pre-Shave Oil', image: '' },
      { step: 3, title: 'Lather', image: '' },
      { step: 4, title: 'Razor Shave', image: '' },
      { step: 5, title: 'Aftershave', image: '' },
    ],
  },
  {
    serviceId: 'm-swedish-massage',
    title: 'Swedish Full Body Massage (60 min)',
    gender: 'men',
    category: 'Massage',
    price: 1299,
    originalPrice: 1699,
    durationMinutes: 60,
    rating: 4.8,
    reviewCount: 4560,
    imageUrl: 'https://images.pexels.com/photos/6560304/pexels-photo-6560304.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Oil Consultation', desc: 'Choose from deep-muscle sesame, relaxing lavender, or energizing eucalyptus oil blend' },
      { step: 2, title: 'Back & Shoulders', desc: 'Therapist focuses first on upper back and shoulders—the primary stress zones for desk workers' },
      { step: 3, title: 'Full Body Flow', desc: 'Swedish effleurage strokes cover arms, legs, and torso to stimulate circulation and lymph flow' },
      { step: 4, title: 'Pressure Point Work', desc: 'Trigger point therapy on neck, lower back, and calves releases deeply held tension knots' },
      { step: 5, title: 'Cool-Down', desc: 'Finish with light feathering strokes; cooling peppermint oil applied to scalp and temples' },
    ],
    procedureSteps: [
      { step: 1, title: 'Oil Select', image: '' },
      { step: 2, title: 'Back & Neck', image: '' },
      { step: 3, title: 'Full Body', image: '' },
      { step: 4, title: 'Pressure Points', image: '' },
      { step: 5, title: 'Cool Down', image: '' },
    ],
  },
  {
    serviceId: 'm-head-neck-shoulder',
    title: 'Head, Neck & Shoulders Massage (30 min)',
    gender: 'men',
    category: 'Massage',
    price: 499,
    originalPrice: 699,
    durationMinutes: 30,
    rating: 4.7,
    reviewCount: 7890,
    imageUrl: 'https://images.pexels.com/photos/6560291/pexels-photo-6560291.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Warm Oil Pour', desc: 'Bhringraj or coconut oil gently warmed and poured along the centre parting of the scalp' },
      { step: 2, title: 'Champi Head Massage', desc: 'Traditional Indian champi technique with firm circular motions on pressure points across the scalp' },
      { step: 3, title: 'Neck & Traps Release', desc: 'Deep kneading of trapezius and neck muscles to relieve tech neck and cervical stiffness' },
      { step: 4, title: 'Shoulder Decompression', desc: 'Cross-fibre friction on deltoids and rhomboids loosens muscle adhesions from prolonged sitting' },
    ],
    procedureSteps: [
      { step: 1, title: 'Warm Oil', image: '' },
      { step: 2, title: 'Head Champi', image: '' },
      { step: 3, title: 'Neck Release', image: '' },
      { step: 4, title: 'Shoulders', image: '' },
    ],
  },
  {
    serviceId: 'm-o3-charcoal-cleanup',
    title: "O3+ Charcoal Cleanup for Men",
    gender: 'men',
    category: 'Cleanup',
    price: 799,
    originalPrice: 999,
    durationMinutes: 45,
    rating: 4.7,
    reviewCount: 6120,
    imageUrl: 'https://images.pexels.com/photos/29189893/pexels-photo-29189893.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Charcoal Foam Wash', desc: 'Activated charcoal face wash deep-cleans pores and removes excess sebum accumulated from outdoor exposure' },
      { step: 2, title: 'Walnut Scrub', desc: 'Walnut bead scrub exfoliates dead skin, reduces tan, and unclogs pores blocked by shaving residue' },
      { step: 3, title: 'Steam + Extraction', desc: 'Herbal steam loosens blackheads and whiteheads; professional extraction done with sterilised tools' },
      { step: 4, title: 'Charcoal Peel Mask', desc: 'O3+ black peel-off mask applied for 15 minutes to pull out remaining impurities and tighten pores' },
      { step: 5, title: 'Ice Globe Finish', desc: 'Ice globes rolled over face to tighten pores and de-puff; SPF moisturizer sealed in' },
    ],
    procedureSteps: [
      { step: 1, title: 'Charcoal Wash', image: '' },
      { step: 2, title: 'Scrub', image: '' },
      { step: 3, title: 'Steam & Extract', image: '' },
      { step: 4, title: 'Peel Mask', image: '' },
      { step: 5, title: 'Ice Finish', image: '' },
    ],
  },
  {
    serviceId: 'm-basic-cleanup',
    title: 'Basic Face Cleanup',
    gender: 'men',
    category: 'Cleanup',
    price: 499,
    originalPrice: 649,
    durationMinutes: 30,
    rating: 4.5,
    reviewCount: 8450,
    imageUrl: 'https://images.pexels.com/photos/30890405/pexels-photo-30890405.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Foam Cleanse', desc: 'Oil-control face wash removes dirt, pollutants, and excess oil for a clean base' },
      { step: 2, title: 'Scrub', desc: 'Mild exfoliating scrub removes dead skin cells and brightens dull complexion in 3 minutes' },
      { step: 3, title: 'Face Pack', desc: 'Multani mitti and neem face pack applied for 10 minutes to absorb oil and reduce acne' },
      { step: 4, title: 'Moisturize', desc: 'Lightweight, non-greasy moisturizer applied to restore hydration without clogging pores' },
    ],
    procedureSteps: [
      { step: 1, title: 'Cleanse', image: '' },
      { step: 2, title: 'Scrub', image: '' },
      { step: 3, title: 'Face Pack', image: '' },
      { step: 4, title: 'Moisturize', image: '' },
    ],
  },
  {
    serviceId: 'm-mani-pedi',
    title: "Men's Manicure + Pedicure",
    gender: 'men',
    category: 'Manicure & Pedicure',
    price: 899,
    originalPrice: 1199,
    durationMinutes: 70,
    rating: 4.6,
    reviewCount: 3210,
    imageUrl: 'https://images.pexels.com/photos/17056222/pexels-photo-17056222.jpeg?auto=compress&cs=tinysrgb&w=800&h=500&fit=crop',
    promoVideoUrl: '',
    ritualSteps: [
      { step: 1, title: 'Warm Soak', desc: 'Hands and feet soaked in warm water with antiseptic salts to soften skin and relax muscles' },
      { step: 2, title: 'Nail Care', desc: 'Nails cleaned, cuticles trimmed and pushed back, nails filed and buffed for a clean, matte finish' },
      { step: 3, title: 'Pumice Scrub', desc: 'Pumice stone and scrub remove dead skin and calluses from heels and pressure zones on feet' },
      { step: 4, title: 'Deep Massage', desc: 'Stimulating hand and foot massage with shea butter cream for relaxation and skin nourishment' },
    ],
    procedureSteps: [
      { step: 1, title: 'Soak', image: '' },
      { step: 2, title: 'Nail Care', image: '' },
      { step: 3, title: 'Scrub', image: '' },
      { step: 4, title: 'Massage', image: '' },
    ],
  },
];

async function seed() {
  console.log('🌱 Seeding Firestore services collection...\n');

  for (const service of services) {
    const docRef = doc(db, 'services', service.serviceId);
    await setDoc(docRef, service);
    console.log(`  ✓ ${service.gender.toUpperCase().padEnd(6)} | ${service.category.padEnd(20)} | ${service.title}`);
  }

  console.log(`\n✅ Successfully seeded ${services.length} services!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});
